server:
  port: 7001

eureka:
  instance:
    # 集群写法
    hostname: eureka7001.com  #eureka服务端的实例名字
  client:
    #表示不向注册中心注册自己
    register-with-eureka: false
    #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
        #defaultZone: http://eureka7002.com:7002/eureka/  #多台机器 支持多个地址 中间使用逗号分割
        defaultZone: http://eureka7002.com:7002/eureka  #多台机器 支持多个地址 中间使用逗号分割
