server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/sbbbb-com/springcloud-config.git
          search-paths:
            - springcloud-config
#          username: 17719357702@163.com
#          password: ***********
          #############

      label: main
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka
