server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
#          uri:  https://github.com/sbbbb-com/springcloud-config.git
          uri:  https://gitee.com/one_one_root/springcloud-config.git
          search-paths:
            - springcloud-config
#          username: 17719357702@163.com
#          password: ***********
          #############
      label:
        - main
        - dev
        #- master

####### #添加rabbitmq的配置#######
  rabbitmq:
      host: 192.168.226.135
      port: 5672
      username: admin
      password: 123
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka


##  rabbitmq 相关配置 暴露bus刷新配置的端点
management:
  endpoints: # 暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

