server:
  port: 80

spring:
  application:
    name: cloud-order-service
  ################【zipkin配置】###################
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率 值介于0到1之间 1表示全部采集
      probability: 1

  ############################################

#  eureka 客户端的配置文件
eureka:
  client:
    # 表示是否将自己注册到EurekaServer 默认为 true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka
